[package]
name = "tide-editor"
edition.workspace = true
version.workspace = true

[dependencies]
tide-core = { workspace = true }
syntect = "5"
pulldown-cmark = "0.12"
unicode-width = "0.2"
log = "0.4"
